#!/usr/bin/env bash
# Registered projects' AGENTS.md must be generated from the canonical template
# plus the project's own overlay, never hand-edited.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
compose="$repo_root/scripts/compose-project-agents.sh"
test_root="$(mktemp -d)"
trap 'rm -rf "$test_root"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }

# 1. The committed files are already in sync with their sources.
"$compose" --check || fail "committed project AGENTS.md is stale; run scripts/compose-project-agents.sh"

# 2. Composition is: generated notice, then the template, then the overlay.
fake="$test_root/repo"
mkdir -p "$fake/scripts/lib" "$fake/skills/setup-project-repo/assets" "$fake/projects/demo"
cp "$compose" "$fake/scripts/"
printf 'demo\tdemo\n' > "$fake/projects/registry.tsv"
printf '# Workflow\n\n- shared rule\n' > "$fake/skills/setup-project-repo/assets/AGENTS.md"
printf '## This Project\n\n- demo rule\n' > "$fake/projects/demo/AGENTS.project.md"
"$fake/scripts/compose-project-agents.sh"
out="$fake/projects/demo/AGENTS.md"
head -1 "$out" | grep -q "Generated by scripts/compose-project-agents.sh" || fail "missing generated notice"
grep -q -- "- shared rule" "$out" || fail "template content missing"
grep -q -- "- demo rule" "$out" || fail "overlay content missing"
[[ "$(grep -n -- '- shared rule' "$out" | cut -d: -f1)" -lt "$(grep -n -- '- demo rule' "$out" | cut -d: -f1)" ]] \
  || fail "overlay must come after the template"

# 3. Running it again changes nothing.
before="$(cat "$out")"
"$fake/scripts/compose-project-agents.sh"
[[ "$before" == "$(cat "$out")" ]] || fail "compose is not idempotent"

# 4. --check catches a hand edit and a template change.
echo "- hand edit" >> "$out"
if "$fake/scripts/compose-project-agents.sh" --check 2>/dev/null; then fail "--check missed a hand edit"; fi
"$fake/scripts/compose-project-agents.sh"
echo "- new shared rule" >> "$fake/skills/setup-project-repo/assets/AGENTS.md"
if "$fake/scripts/compose-project-agents.sh" --check 2>/dev/null; then fail "--check missed a template change"; fi

# 5. Projects without an overlay are left alone.
mkdir -p "$fake/projects/plain"
printf 'plain\tplain\n' >> "$fake/projects/registry.tsv"
"$fake/scripts/compose-project-agents.sh"
[[ ! -e "$fake/projects/plain/AGENTS.md" ]] || fail "created AGENTS.md for a project without an overlay"

echo "compose-project-agents tests passed"
