#!/usr/bin/env bash
# Builds each registered project's AGENTS.md from the canonical workflow
# template plus that project's own overlay, so a workflow rule is edited once
# and reaches every project. --check reports stale files without writing.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
template="$repo_root/skills/setup-project-repo/assets/AGENTS.md"
check_only=false

case "${1:-}" in
  --check) check_only=true ;;
  "") ;;
  *) echo "Usage: scripts/compose-project-agents.sh [--check]" >&2; exit 2 ;;
esac

compose_project() {
  local project_name="$1"
  local overlay="$repo_root/projects/$project_name/AGENTS.project.md"
  local output="$repo_root/projects/$project_name/AGENTS.md"

  [[ -f "$overlay" ]] || return 0

  local composed
  composed="$(
    printf '%s\n' "<!-- Generated by scripts/compose-project-agents.sh from skills/setup-project-repo/assets/AGENTS.md and projects/$project_name/AGENTS.project.md. Edit those, not this file. -->"
    printf '\n'
    cat "$template"
    printf '\n'
    cat "$overlay"
  )"

  if [[ "$check_only" == true ]]; then
    if [[ ! -f "$output" || "$composed" != "$(cat "$output")" ]]; then
      echo "Stale: projects/$project_name/AGENTS.md" >&2
      return 1
    fi
    return 0
  fi

  if [[ -f "$output" && "$composed" == "$(cat "$output")" ]]; then
    return 0
  fi
  printf '%s\n' "$composed" > "$output"
  echo "Composed projects/$project_name/AGENTS.md"
}

status=0
while IFS=$'\t' read -r project_name _checkout_name; do
  [[ -n "$project_name" && "${project_name:0:1}" != "#" ]] || continue
  compose_project "$project_name" || status=1
done < "$repo_root/projects/registry.tsv"
exit "$status"
